[package]
name = "perplexity"
version = "0.2.0"
edition = "2024"
license = "Apache-2.0"

[lib]
path = "src/perplexity.rs"
crate-type = ["cdylib"]

[dependencies]
serde = "1"
zed_extension_api = "0.1.0"
